### PR TITLE
[Enhancement] Webpack integration and Node support

### PR DESCRIPTION
**Pull request by Craga89**
Allows easier builds without the need for ReactProvider and D3Provider files via the use of `webpack` instead of the existing `browserify` functionality. Also included new minified build w/ sourcemap for browser users of the library.

Previously node support was lacking due to non-compiled ES6 syntax in the src/ directory. Added a `compile` step to produce standard `lib` directory with the ES5 code and pointed the `package.json`s `main` key to `lib/index.js` instead.

Also renamed all .js files to .jsx where appropriate and updated to the latest package dependencies.

### CODE REVIEW

**Comment by codesuki** [comment]
Hey thanks for the pull request! 
I already added the /lib directory with es5 code some time ago (see master branch). 
But I like the idea of changing to webpack, already planned to do that so I will take your webpack config and set it up!

P.S. some files in your pull req. are duplicated now (LineChart.js and LineChart.jsx for exmple). 
Since I already renamed them there is no need to fix that though.

**Comment by Craga89** [comment]
Sweet, didn't notice the lib directory when I was working on it! Great job on the components

**Comment by codesuki** [comment]
It gets deleted after npm publish/install ;)
Thank you! Animations are half way done but the code got a little bit more messy since Brush support.

**Comment by jnak** [comment]
nice!

**Pull request closed without merging**
