### PR TITLE
Update to 0.14.0 stable

### PR DESCRIPTION
**Pull request by nicolabortignon**

### CODE REVIEW

**Comment by nicolabortignon** [comment]
@codesuki please also create a tag out of this, so is installed by default.

**Comment by codesuki** [comment]
You mean a release?

**Comment by nicolabortignon** [comment]
yep sorry, a release.

**Comment by codesuki** [comment]
yeah i'll do that :) thanks!

**Comment by Budmore** [comment]
Hi, is there a specific reason to increase the required React version to 0.14?
Because this change will break my current project.

**Comment by nicolabortignon** [comment]
IMHO the react community is pushing a lot to keep libraries on the bleeding edge. The change from 0.13 to 0.14 is substantial and we should align.
You can still required a previous release of this library by setting your dependency package.json.

**Comment by Budmore** [comment]
Sure it's nice to have the newest library, but this need some time to all of them to update to the latest version.
In my project we decide to stay at v0.13.3, because some of our dependency modules are not compatible with 0.14 yet.

So, if react-d3-component is backward compatible it no need to limit the version. 
```
peerDependencies: {
    "react": ">=0.13.1"
}
```

**Comment by codesuki** [comment]
React 0.14 adds support for the ClipPath attribute which until now was done with some ugly hack. 
I already added that so in future releases we definitely need 0.14.
Maybe you can depend on the old version until your other dependencies catch up?

If you need the new wavechart I can make a small release for you that depends on 0.13 and includes the wavechart.

**Comment by Budmore** [comment]
It's all right, there's no need to create small release. I will create my own custom version in the fork.

**Comment by codesuki** [comment]
Hope it works out well for you!

**Pull request merged**
