### PR TITLE
support react 15

### PR DESCRIPTION
**Pull request by RahavLussato**

### CODE REVIEW

**Comment by codesuki** [comment]
Hi! thanks for the pullreq! Did the >=0.14.0 not work? 
I am not really used to the versioning. Would be nice if you could tell me the merits of the new one and the demerits of the old one :)

**Comment by RahavLussato** [comment]
the ">=0.14.0" didn't work, the old one will not support react new version V15 and up, the new one will support the versions of react that it supported before and the new one.

**Comment by codesuki** [comment]
Thanks! Mistook the versioning somehow.
`"react": "^0.14.0 || ^15.0.0"` this would be correct too I guess?

**Comment by codesuki** [comment]
I'll merge and make a new release.

**Comment by codesuki** [comment]
I just realized the 15.0.0 and 0.15.0 difference.. totally didn't see that before.

**Pull request merged**
