### PR TITLE
Fix placement of axis label when axis' orientation is on the right.

### PR DESCRIPTION
**Pull request by serveace**
If the axis is on the right, the label ends up on top of the tick marks.  With this check, it'll move it .75em in the appropriate direction.  Built and test on my local environment and it looks good.

### CODE REVIEW

**Comment by codesuki** [comment]
Hey there! Thanks for the pullreq and sorry for the late response. Was on holiday.
I checked your change and thought that changing it to -1.25em looks even better. What do you think? Will you give it a try and send another commit or should  I just merge your pullreq. and amend the number?

**Comment by codesuki** [comment]
BTW I noticed putting the Y axis on the right side makes the X axis label hug the Y axis which seems weird. Don't have time to change it now but allowing to move the label right or left could be good.

**Comment by serveace** [comment]
-1.25em looks good.  PR updated.

**Comment by codesuki** [comment]
Great! thank you :)

**Pull request merged**
