### PR TITLE
Update codestyle and building

### PR DESCRIPTION
**Pull request by solomein**
## Building
I have updated the dev dependencies to the newest versions. In consequence I also had to update the configs. I added a eslint to resolve a possible conflict with the global version of package.

Added `lint` command.

## Coding style
I would like to propose some changes.

I have updated the eslint configuration, added more rules. All files have been fixed in accordance with the rules (indents, spacing, declarations, etc., have been normalized).

Other changes:
* Using ES2015 modules
* Destructuring `React.PropTypes`
* Getting rid of the list destructuring as a regular way of declaration.

### CODE REVIEW

**Comment by codesuki** [comment]
Great! A long overdue refresh :)
Thank you!

One question: What exactly do you mean by `Getting rid of the list destructuring asa regular way of declaration`? 

I thought you were talking about this:
```const {
+            data,
+            area,
+            colorScale,
+            values,
+            label,
+            onMouseEnter,
+            onMouseLeave
+        } = this.props;```

But since it's still there I am mistaken.

**Comment by codesuki** [comment]
Could probably delete the jshint file since it's not longer needed.

**Comment by codesuki** [comment]
I get this warning now: 

```
You have mistakenly installed the `babel` package, which is a no-op in Babel 6.
Babel's CLI commands have been moved from the `babel` package to the `babel-cli` package.

    npm uninstall babel
    npm install babel-cli

See http://babeljs.io/docs/usage/cli/ for setup instructions.
```

**Comment by codesuki** [comment]
What tool do you use to format the source? 
My emacs setup ignores the .eslint file it seems. So I have to figure something out.

**Comment by solomein** [comment]
@codesuki Mostly, I use Atom and WebStorm. The `--fix` option automatically fixes not all problems.

 **List destructuring**
```js
let [data,
     innerWidth,
     innerHeight,
     xScale,
     yScale,
     xIntercept,
     yIntercept] = [this._data,
                    this._innerWidth,
                    this._innerHeight,
                    this._xScale,
                    this._yScale,
                    this._xIntercept,
                    this._yIntercept];
```

**Comment by codesuki** [comment]
Oh this one! True, haha. Totally missed it. Sorry.

**Comment by codesuki** [comment]
I had to make a small change, replacing babel with babel-cli in package.json. Already pushed it.

**Pull request merged**
