### PR TITLE
Allow any renderable node to be passed as the HTML of Tooltip

### PR DESCRIPTION
**Pull request by wemcdonald**
This allows Tooltips to contain anything that can be rendered: numbers, strings, elements or an array containing these types.

### CODE REVIEW

**Comment by codesuki** [comment]
Thanks! Will check :)

**Comment by codesuki** [comment]
Just some update: 
I am rewriting a lot of code now and it will result in also being able to pass anything to the tooltip!

**Comment by tylerkahn** [comment]
+1 would be useful for me

**Comment by codesuki** [comment]
Thanks for the feedback! I am extremely busy but I can see it clear up a little soon :)

**Comment by codesuki** [comment]
I will change that in my branch since I can't automatically merge anymore. Probably because of the file in dist/
Thanks for your contribution and sorry for responding so late!

**Pull request closed without merging**
