### PR TITLE
Migration to 5 version D3

### PR DESCRIPTION
**Pull request by retyui**
Remove .npmignore used `package.json -> files` (check result `npm pack`)
Update D3 version to latest
Did the formatting `eslint --fix`

### CODE REVIEW

**Comment by retyui** [comment]
https://github.com/codesuki/react-d3-components/issues/155

**Comment by codesuki** [comment]
That was quick! Thanks for the PR. Please let me check it on monday, I am away for the weekend. Thanks again!

**Comment by retyui** [comment]
There are still many problems, I now understand what this method does

https://github.com/codesuki/react-d3-components/blob/master/src/StackDataMixin.jsx#L26-L52

**Comment by codesuki** [comment]
Is this PR still WIP? 
If you need me to explain any part of the code, let me know!

**Comment by retyui** [comment]
@codesuki 
I almost finished left the most difficult for me : this is a change for `d3.stack` [StackDataMixin.jsx#L27-L39](https://github.com/retyui/react-d3-components/blob/d3-version-5/src/StackDataMixin.jsx#L27-L39)
mentioned by @PierreGUI https://github.com/codesuki/react-d3-components/issues/133#issuecomment-308734293


## Fast check result
```
git clone https://github.com/retyui/react-d3-components -b d3-version-5
yarn
yarn watch
```
And open: http://localhost:3000/example/d3-v5/

**Comment by codesuki** [comment]
Great! I'll have a look later today. Thanks!

**Comment by retyui** [comment]
@codesuki Well, what do you say?

**Comment by codesuki** [comment]
Sorry, in the middle of release preparations. I'll need a few more days until I have time to check it out.

**Comment by codesuki** [comment]
What happened?

**Comment by retyui** [comment]
Do not worry, I want to do everything in stages. Multiple steps for migration

**Comment by retyui** [comment]
@codesuki 
This is a list of changes that need to be made so that migration is as productive as possible:
1) Add lint-staged, prettier
2) Add test form components
3) Replace mixins to hocs
4) Migrate to d3 version 5
Do you agree with these changes?

**Comment by codesuki** [comment]
Yes that is a reasonable list. Step 3 is mostly useful for React upgrades, but super useful.

**Pull request closed without merging**
